[package]
name = "hls_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crdts = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
tokio = { workspace = true }